"""empty message

Revision ID: 47168028e699
Revises: 8692d2d51066
Create Date: 2020-08-31 05:13:48.638348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47168028e699'
down_revision = '8692d2d51066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
